
name: Sample-book-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ... build success ...
        run: echo Building of node aplication is starting ...

      - name: ... check node version ...
        run: node -v 

  deploy-dev:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: ... deploy success ...
        run: echo Deployment to DEV has started ...
  
  tests-dev:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      - name: ... tests success ...
        run: echo Testing on DEV has started ...

  deploy-stg:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: ... deploy success ...
        run: echo Deployment to STG has started ...
  
  tests-stg:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      - name: ... tests success ...
        run: echo Testing on STG has started ...

  deploy-prd:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: ... deploy success ...
        run: echo Deployment to PRD has started ...
  
  tests-prd:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      - name: ... tests success ...
        run: echo Testing on PRD has started ...
